# Generated by Django 6.0.6 on 2026-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
