# Generated by Django 6.0.6 on 2026-07-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='edit_locked',
            field=models.BooleanField(default=False),
        ),
    ]
