# Generated by Django 6.0.6 on 2026-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
